language: node_js

node_js:
  - "12"

script:
    # - npm install
    # - npm test
    # - npm run start
    - CI=false npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project readlproto --token $FIREBASE_TOKEN