import book1 from '../assets/img/book1.png'
import book2 from '../assets/img/book2.png'
import book3 from '../assets/img/book3.png'
import book4 from '../assets/img/book4.png'
import book5 from '../assets/img/book5.png'

export const homeScreenBookData = [{
    id: 1,
    title: 'I Think I Love You',
    author: 'Dhia Amjad',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book1,
} , {
    id: 2,
    title: 'Dancing In The Dark',
    author: 'Alya Aqibta',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book2,
} , {
    id: 3,
    title: 'Fri-End Zone',
    author: 'RIDDLE ORIGINAL',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book3,
} , {
    id: 4,
    title: 'Sunset',
    author: 'Chloe Moretz',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book4,
} , {
    id: 5,
    title: 'The Steps to Him',
    author: 'Achanchill',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book5,
} , {
    id: 6,
    title: 'I Think I Love You',
    author: 'Dhia Amjad',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book1,
}]

export const moreData = [{
    id: 1,
    title: 'I Think I Love You',
    author: 'Dhia Amjad',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book1,
} , {
    id: 2,
    title: 'Dancing In The Dark',
    author: 'Alya Aqibta',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book2,
} , {
    id: 3,
    title: 'Fri-End Zone',
    author: 'RIDDLE ORIGINAL',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book3,
} , {
    id: 4,
    title: 'Sunset',
    author: 'Chloe Moretz',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book4,
} , {
    id: 5,
    title: 'The Steps to Him',
    author: 'Achanchill',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book5,
} , {
    id: 6,
    title: 'I Think I Love You',
    author: 'Dhia Amjad',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book1,
} , {
    id: 7,
    title: 'Dancing In The Dark',
    author: 'Alya Aqibta',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book2,
} , {
    id: 8,
    title: 'Fri-End Zone',
    author: 'RIDDLE ORIGINAL',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book3,
} , {
    id: 9,
    title: 'Sunset',
    author: 'Chloe Moretz',
    likeCount: '100',
    viewCount: '200',
    bookmarkCount: '100',
    bookImage: book4,
}]